// src/components/MathProblem.vue
<template>
  <div class="question">
    <vue-mathjax :formula="problem.question" :options="TEX_OPTIONS" />
    <div class="answer-container">
      <span
        >{{
          problem.answerType === AnswerType.AllOrdered
            ? "Answers in order:"
            : problem.answerType === AnswerType.Any
            ? "Answers (only one needed):"
            : problem.answers.length === 1
            ? "Answer:"
            : "Answers:"
        }}
      </span>
      <button
        v-if="!answerShown"
        @click="
          () => {
            answerShown = true;
          }
        "
        class="show-answer-button"
      ></button>
      <span v-show="answerShown"
        ><vue-mathjax
          :formula="problem.answers.map((a) => '$' + a + '$').join(', ')"
          :options="TEX_OPTIONS"
      /></span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from "vue";
import { AnswerType, Problem } from "../math-types";

const TEX_OPTIONS = reactive({
  tex2jax: {
    inlineMath: [["$", "$"]],
    displayMath: [["$$", "$$"]],
    processEscapes: true,
    processEnvironments: true,
  },
});

const answerShown = ref(false);

const { problem } = defineProps<{ problem: Problem }>();
</script>

// src/components/display/MathProblem.tsx
import { useEffect, useState } from "react";
import { AnswerType, Problem } from "../../lib/math/math-types";
import { MathJax } from "better-react-mathjax";
import { Card, Flex } from "@tremor/react";

type MathProblemProps = {
  problem: Problem;
};

export default function MathProblem({ problem }: MathProblemProps) {
  const [answerShown, setAnswerShown] = useState(false);
  return (
    <Card className="basis-1/5 shrink-0 grow flex flex-col justify-between">
      <MathJax className="dark:text-white">{problem.question}</MathJax>
      <div>
        <div className="mt-4 dark:text-white">
          {!answerShown ? (
            <button
              onClick={() => {
                setAnswerShown(true);
              }}
              className="bg-blue-400 rounded-md px-3 py-1 active:bg-blue-500 whitespace-nowrap"
            >
              Show Answer
            </button>
          ) : (
            <>
              <span className="font-bold">
                {problem.answerType === AnswerType.AllOrdered
                  ? "Answers in order:"
                  : problem.answerType === AnswerType.Any
                  ? "Answers (only one needed):"
                  : problem.answers.length === 1
                  ? "Answer:"
                  : "Answers:"}
              </span>
              <MathJax>{problem.answers.join(", ")}</MathJax>
            </>
          )}
        </div>
      </div>
    </Card>
  );
}
