// src/App.tsx
import classNames from "classnames";
import { Link, NavLink, Outlet } from "react-router-dom";

export default function App() {
  return (
    <>
      <header className="no-print border-b-4 border-black justify-between flex pb-2 mb-2">
        <h1 className="text-xl">Academic Team Quiz</h1>
        <div className="flex items-center gap-4 shrink">
          {[
            { to: "/", name: "Quiz Yourself!" },
            { to: "/set", name: "Create A Set" },
            { to: "/math", name: "Practice Math!" },
          ].map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              className={({ isActive }) =>
                classNames("hover:underline", {
                  underline: isActive,
                })
              }
            >
              {item.name}
            </NavLink>
          ))}
        </div>
      </header>
      <Outlet />
    </>
  );
}

// src/App.vue
<script setup lang="ts"></script>

<template>
  <header v-if="$route.name !== 'login'" class="no-print">
    <h1>Academic Team Quiz</h1>
    <div class="links">
      <router-link to="quiz" class="link" active-class="active"
        >Quiz Yourself!</router-link
      >
      <router-link to="set" class="link" active-class="active"
        >Create A Set!</router-link
      >
      <router-link to="math" class="link" active-class="active"
        >Practice Math!</router-link
      >
    </div>
  </header>
  <router-view></router-view>
</template>
